# Metodología {#metodo}

Adoptamos la Clasificación Internacional de Delitos con Fines Estadísticos (ICCS por sus siglas en inglés) para contar con un marco general que incluye conceptos, definiciones y principios sobre delitos convenidos intencionalmente. Este instrumento fue elaborado por la Oficina de las Naciones Unidas contra la Droga y el Delito (UNODC) y liberado en el 2015 [@UNODC2015].

La ICCS proporciona un marco conceptual común para elaborar y comparar de forma sistemática datos estadísticos obtenidos en cualquiera de las etapas del proceso de justicia penal, así como en encuestas de victimización (ICCS, 2015; Pág. 7). La ICCS al ofrecer un marco general, sirve a nivel nacional para estructurar y organizar datos estadísticos que obedezcan a categorías analíticas y no jurídicas. El uso de conceptos y definiciones estandarizadas no sólo permite la recopilación, el análisis y la difusión sistemática de datos, también facilita el análisis del delito (Ibidem).

De las muchas razones para tomar esa decisión está que la función principal de los observatorios de prensa es recabar información para conformar una base estadística sobre la ocurrencia del delito interpersonal violento en las regiones del país y con ella analizar sus móviles, distribución y evolución. No está demás destacar el valor que tiene que haya sido el OVV la primera organización del país en adoptar el uso del ICCS para sistematizar sus datos sobre el delito violento en nuestro medio.

Es cierto que la información proporcionada por los medios que han asegurado los observatorios es en muchos casos insuficiente para cumplimentar satisfactoriamente el instrumento, pero el estudio de los conceptos, definiciones y principios del ICCS es un requisito indispensable para mejorar las capacidades de los observatorios en el llenado del instrumento de captura de datos.

La preocupación mayor sobre la falta de comparabilidad, que es real, aún con la estandarización que supone el uso de la ICCS, está en la variabilidad de las fuentes de información por medio de los cuales los observatorios regionales recopilan sus datos. Por un lado los medios informativos siguen políticas editoriales distintas y obedecen a intereses de diversa naturaleza y por otro los periodistas o las personas que sirven de informantes emplean diferentes aproximaciones y criterios en el reporte de los sucesos. Expresado en términos estadísticos, decimos que hay sesgos de selección y variabilidad no controlada en el tratamiento del dato por parte de los generadores de la información. Desde una perspectiva metodológica, el dato estadístico agregado que producen los observatorios como estimación del delito violento ocurrido en sus regiones está inseparablemente asociado, técnicamente diríamos confundido, con las particularidades del proceso de recopilación de datos.

La ICCS constituye un marco general y no se puede pretender que cubra lo particular del delito de todos los países. Podemos y debemos ampliar, siempre que sea necesario, los tipos delictuales no incluidos pero que ocurran con frecuencia en el país, claro está siendo coherentes con lo establecido en el marco general del ICCS.

